pool:
  vmImage: ubuntu-latest

stages:
- stage: SAST
  jobs:
  - job: Job
    displayName: 'SAST sonarCloud'
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'spring-boot-kubernetes'
        organization: 'pfcanales'
        projectKey: 'pfcanales-spring-boot-kubernetes'
        projectName: 'spring-boot-kubernetes'

    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
        sqMavenPluginVersionChoice: 'latest'

    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'
    
    - task: sonarcloud-buildbreaker@2
      inputs:
        SonarCloud: 'spring-boot-kubernetes'
        organization: 'pfcanales'
    
- stage: SCA
  jobs:
  - job: 
    displayName: 'SCA Dependency Check'
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    
    - task: dependency-check-build-task@6
      inputs:
        projectName: 'spring-boot-kubernetes'
        scanPath: '$(Build.SourcesDirectory)/target'
        format: 'HTML'

- stage: DAST
  jobs:
  - job: Job
    displayName: 'DAST Container Security'
    steps:

    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
      
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
      
    - task: Docker@2
      inputs:
        containerRegistry: 'docker-spring-boot'
        repository: 'patriciopcg/spring-boot'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'
    
    - script: |
          sudo apt-get install -y rpm
          wget https://github.com/aquasecurity/trivy/releases/download/v0.27.1/trivy_0.27.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.27.1_Linux-64bit.deb
          trivy image patriciopcg/spring-boot:latest
      displayName: Image Scan
    
    - task: Docker@2
      inputs:
        containerRegistry: 'docker-spring-boot'
        repository: 'patriciopcg/spring-boot'
        command: 'push'
        tags: 'latest'